### ISSUE TITLE
Version 1.2 only Contao 5?

### ISSUE THREAD

**Issue by operatorone** [heimseiten/contao-article-image-bundle#1]
Hi, ich wollte gerne die Erweiterung in eine 4.13 Instanz installieren und die neuste Version wurde verweigert, weil es eine Abhängigkeit zu Contao 5 gibt. Muss ich die Version 1.1* für Contao 4.13 verwenden?

**Comment by heimseiten** [comment]
Ja, die neueste Version ist nur noch zu Contao 5 kompatibel. Von den Funktionen hat sich aber auch nichts in der 1.2 geändert.

**Comment by heimseiten** [comment]
Ja, die neueste Version ist nur noch zu Contao 5 kompatibel. Von den Funktionen hat sich aber auch nichts in der 1.2 geändert.
